services:
  home:
    container_name: home
    build:
      context: .
      dockerfile: ./apps/home/Dockerfile
      target: development
    restart: unless-stopped
    user: "1000:1000"
    env_file:
      - ./apps/home/.env
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for hot reload
      - ./apps/home:/app/apps/home
      - ./packages:/app/packages
      - ./package.json:/app/package.json
      - ./turbo.json:/app/turbo.json
      # Mount node_modules for dependencies
      - ./node_modules:/app/node_modules
      - ./apps/home/node_modules:/app/apps/home/node_modules
    working_dir: /app/apps/home
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - PATH=/app/apps/home/node_modules/.bin:/app/node_modules/.bin:$PATH
    command: ["npm", "run", "dev"]
